name: Feed me

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  feed-me:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install tinyfeed
        run: go install github.com/TheBigRoomXXL/tinyfeed@latest

      - name: Fetch feeds
        run: tinyfeed --input feeds.txt --output public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/action-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          cname: feeds.jbowdre.lol

